#############################################################################
# Makefile for building: XBian-installer
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  xbian-installer.pro
# Template: app
# Command: /home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile xbian-installer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/linux-g++ -I. -I../../Qt5.2.0/5.2.0-rc1/gcc_64/include -I../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets -I../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork -I../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml -I../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui -I../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64 -Wl,-rpath,/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib -lQt5Widgets -lQt5Network -lQt5Xml -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		installer.cpp \
		version.cpp \
		diskwriter_unix.cpp qrc_rsc.cpp \
		moc_installer.cpp \
		moc_diskwriter.cpp \
		moc_diskwriter_unix.cpp
OBJECTS       = main.o \
		installer.o \
		version.o \
		diskwriter_unix.o \
		qrc_rsc.o \
		moc_installer.o \
		moc_diskwriter.o \
		moc_diskwriter_unix.o
DIST          = ../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/uic.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/lex.prf \
		xbian-installer.pro \
		rsc.qrc \
		xbian-installer.pro
QMAKE_TARGET  = XBian-installer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = XBian-installer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_installer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: xbian-installer.pro ../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/uic.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/lex.prf \
		xbian-installer.pro \
		rsc.qrc \
		/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Widgets.prl \
		/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Gui.prl \
		/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Core.prl \
		/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Network.prl \
		/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Xml.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile xbian-installer.pro
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/shell-unix.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/unix.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/linux.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/qconfig.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/spec_post.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/declarative_debug.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/qt.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/resources.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/moc.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/uic.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.2.0/5.2.0-rc1/gcc_64/mkspecs/features/lex.prf:
xbian-installer.pro:
rsc.qrc:
/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Widgets.prl:
/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Gui.prl:
/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Core.prl:
/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Network.prl:
/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/lib/libQt5Xml.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile xbian-installer.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/XBian-installer1.0.0 || mkdir -p .tmp/XBian-installer1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/XBian-installer1.0.0/ && $(COPY_FILE) --parents rsc.qrc .tmp/XBian-installer1.0.0/ && $(COPY_FILE) --parents installer.h diskwriter.h version.h diskwriter_unix.h zlib.h zconf.h .tmp/XBian-installer1.0.0/ && $(COPY_FILE) --parents main.cpp installer.cpp version.cpp diskwriter_unix.cpp .tmp/XBian-installer1.0.0/ && $(COPY_FILE) --parents installer.ui .tmp/XBian-installer1.0.0/ && (cd `dirname .tmp/XBian-installer1.0.0` && $(TAR) XBian-installer1.0.0.tar XBian-installer1.0.0 && $(COMPRESS) XBian-installer1.0.0.tar) && $(MOVE) `dirname .tmp/XBian-installer1.0.0`/XBian-installer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/XBian-installer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_rsc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rsc.cpp
qrc_rsc.cpp: rsc.qrc \
		icon.ico \
		refresh.png
	/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/bin/rcc -name rsc rsc.qrc -o qrc_rsc.cpp

compiler_moc_header_make_all: moc_installer.cpp moc_diskwriter.cpp moc_diskwriter_unix.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_installer.cpp moc_diskwriter.cpp moc_diskwriter_unix.cpp
moc_installer.cpp: ../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QDialog \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qdialog.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qflags.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstring.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qchar.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmargins.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrect.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsize.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpalette.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcolor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qrgb.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpair.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qbrush.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvector.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qmatrix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpolygon.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qregion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qline.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtransform.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qimage.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpixmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qhash.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfont.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcursor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qset.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurlquery.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qvector2d.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/QtXml \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/QtXmlDepends \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QtCore \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QtCoreDepends \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpauseanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvariantanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeasingcurve.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextcodec.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qendian.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlibraryinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatetime.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbuffer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdir.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfileinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdiriterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfileselector.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QObject \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QStringList \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlockfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qloggingcategory.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocess.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qresource.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsavefile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsettings.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstandardpaths.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtemporarydir.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QScopedPointer \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtemporaryfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlistmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeventloop.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasictimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmath.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetaobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimedata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedmemory.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsignalmapper.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsocketnotifier.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtranslator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qwineventnotifier.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimedatabase.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimetype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfactoryinterface.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlibrary.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qplugin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpluginloader.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/quuid.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstracttransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeventtransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfinalstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qhistorystate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsignaltransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstatemachine.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qexception.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuture.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfutureinterface.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrunnable.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qresultstore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuturewatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qreadwritelock.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsemaphore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthread.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthreadpool.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthreadstorage.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qwaitcondition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbitarray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcache.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcollator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcommandlineoption.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcommandlineparser.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlinkedlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qqueue.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstack.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimeline.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimezone.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qxmlstream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtcoreversion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qtxmlglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qdom.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qxml.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qtxmlversion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qssl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFlags \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QList \
		version.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QString \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFile \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QXmlStreamReader \
		installer.h
	/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/bin/moc $(DEFINES) $(INCPATH) installer.h -o moc_installer.cpp

moc_diskwriter.cpp: ../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QObject \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qflags.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstring.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qchar.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QString \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QStringList \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpair.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringmatcher.h \
		diskwriter.h
	/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/bin/moc $(DEFINES) $(INCPATH) diskwriter.h -o moc_diskwriter.cpp

moc_diskwriter_unix.cpp: diskwriter.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QObject \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qflags.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstring.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qchar.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QString \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QStringList \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpair.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFile \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfiledevice.h \
		diskwriter_unix.h
	/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/bin/moc $(DEFINES) $(INCPATH) diskwriter_unix.h -o moc_diskwriter_unix.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_installer.h
compiler_uic_clean:
	-$(DEL_FILE) ui_installer.h
ui_installer.h: installer.ui
	/home/koenkk/Qt5.2.0/5.2.0-rc1/gcc_64/bin/uic installer.ui -o ui_installer.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp installer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QDialog \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qdialog.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qflags.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstring.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qchar.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmargins.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrect.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsize.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpalette.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcolor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qrgb.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpair.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qbrush.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvector.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qmatrix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpolygon.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qregion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qline.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtransform.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qimage.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpixmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qhash.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfont.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcursor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qset.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurlquery.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qvector2d.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/QtXml \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/QtXmlDepends \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QtCore \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QtCoreDepends \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpauseanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvariantanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeasingcurve.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextcodec.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qendian.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlibraryinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatetime.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbuffer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdir.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfileinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdiriterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfileselector.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QObject \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QStringList \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlockfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qloggingcategory.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocess.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qresource.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsavefile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsettings.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstandardpaths.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtemporarydir.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QScopedPointer \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtemporaryfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlistmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeventloop.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasictimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmath.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetaobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimedata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedmemory.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsignalmapper.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsocketnotifier.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtranslator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qwineventnotifier.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimedatabase.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimetype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfactoryinterface.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlibrary.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qplugin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpluginloader.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/quuid.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstracttransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeventtransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfinalstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qhistorystate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsignaltransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstatemachine.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qexception.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuture.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfutureinterface.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrunnable.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qresultstore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuturewatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qreadwritelock.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsemaphore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthread.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthreadpool.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthreadstorage.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qwaitcondition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbitarray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcache.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcollator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcommandlineoption.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcommandlineparser.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlinkedlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qqueue.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstack.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimeline.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimezone.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qxmlstream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtcoreversion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qtxmlglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qdom.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qxml.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qtxmlversion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qssl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFlags \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QList \
		version.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QString \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFile \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QXmlStreamReader \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QApplication \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qguiapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qinputmethod.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QMessageBox \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

installer.o: installer.cpp installer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QDialog \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qdialog.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qflags.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstring.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qchar.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmargins.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrect.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsize.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpalette.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcolor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qrgb.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpair.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qbrush.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvector.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qmatrix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpolygon.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qregion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qline.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtransform.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qimage.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpixmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qhash.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfont.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcursor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qset.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurlquery.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qvector2d.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/QtXml \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/QtXmlDepends \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QtCore \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QtCoreDepends \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpauseanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvariantanimation.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeasingcurve.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextcodec.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qendian.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlibraryinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatetime.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnumeric.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbuffer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdir.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfileinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdiriterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfileselector.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QObject \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QStringList \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlockfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qloggingcategory.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocess.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qresource.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsavefile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsettings.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstandardpaths.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtemporarydir.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QScopedPointer \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtemporaryfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlistmodel.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qjsonobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeventloop.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasictimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmath.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetaobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimedata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedmemory.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsignalmapper.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsocketnotifier.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtranslator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qwineventnotifier.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimedatabase.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmimetype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfactoryinterface.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlibrary.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qplugin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpluginloader.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/quuid.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstractstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qabstracttransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeventtransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfinalstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qhistorystate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsignaltransition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstatemachine.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qexception.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuture.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfutureinterface.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrunnable.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qresultstore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfuturewatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qreadwritelock.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsemaphore.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthread.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthreadpool.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qthreadstorage.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qwaitcondition.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbitarray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcache.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcollator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcommandlineoption.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcommandlineparser.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlinkedlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qqueue.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstack.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimeline.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtimezone.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qxmlstream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtcoreversion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qtxmlglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qdom.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qxml.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtXml/qtxmlversion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QSslConfiguration \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qssl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFlags \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QList \
		version.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QString \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFile \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QXmlStreamReader \
		ui_installer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QFileDialog \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qfiledialog.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QUrl \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QNetworkReply \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qnetworkreply.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QIODevice \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QVariant \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/QNetworkRequest \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QSharedDataPointer \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QMessageBox \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qmessagebox.h \
		diskwriter_windows.h \
		diskwriter.h \
		diskwriter_unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o installer.o installer.cpp

version.o: version.cpp version.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QString \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstring.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qchar.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qflags.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFile \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QCryptographicHash \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcryptographichash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o version.o version.cpp

diskwriter_unix.o: diskwriter_unix.cpp diskwriter_unix.h \
		diskwriter.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QObject \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qnamespace.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobal.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qconfig.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfeatures.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_power.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_mips.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_s390.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_x86.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qatomic_unix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmutex.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlogging.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qflags.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstring.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qchar.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qbytearray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrefcount.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qarraydata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiterator.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmetatype.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qisenum.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QString \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QStringList \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringlist.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdatastream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qiodevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpair.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qregexp.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QFile \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfile.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QDebug \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdebug.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qhash.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qtextstream.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qlocale.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvariant.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qshareddata.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qvector.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qpoint.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qset.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/QApplication \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qeventloop.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsize.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcursor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qmargins.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qrect.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpalette.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qcolor.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qrgb.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qbrush.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qmatrix.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpolygon.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qregion.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qline.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtransform.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpainterpath.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qimage.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qpixmap.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfont.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qevent.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurl.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qurlquery.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qvector2d.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qtouchdevice.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qguiapplication.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtGui/qinputmethod.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QDir \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qdir.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qfileinfo.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QProcess \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/qprocess.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtCore/QTextStream \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtZlib/zlib.h \
		../../Qt5.2.0/5.2.0-rc1/gcc_64/include/QtZlib/zconf.h \
		zlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskwriter_unix.o diskwriter_unix.cpp

qrc_rsc.o: qrc_rsc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rsc.o qrc_rsc.cpp

moc_installer.o: moc_installer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_installer.o moc_installer.cpp

moc_diskwriter.o: moc_diskwriter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskwriter.o moc_diskwriter.cpp

moc_diskwriter_unix.o: moc_diskwriter_unix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskwriter_unix.o moc_diskwriter_unix.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

